const mongoose = require('mongoose');

const paymentSchema = new mongoose.Schema({
    orderId: { // for our database which we will store
        type: mongoose.Schema.Types.ObjectId,
        required: true
    },
    razorpayPaymentId: {
        type: String,
    },
    razorpayOrderId: { // Generated by Razorpay
        type: String,
        required: true
    },
    signature: {
        type: String,
    },
    status: {
        type: String,
        enum: ['PENDING', 'COMPLETED', 'FAILED'],
        default: 'PENDING'
    },
    user: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
    },
    price: {
        amount: {
            type: Number,
            required: true
        },
        currency: {
            type: String,
            required: true,
            default: 'INR',
            enum: ['USD', 'EUR', 'INR'],
        }
    }
}, { timestamps: true });

const paymentModel = mongoose.model('Payment', paymentSchema);

module.exports = paymentModel;
